// Offline cache. Bump VERSION when data or app changes.
const VERSION = "v17";
const ASSETS = [
 "./",
 "index.html",
 "css/app.css",
 "js/core.js",
 "js/view-home.js",
 "js/view-sort.js",
 "js/view-values.js",
 "js/view-tools.js",
 "js/view-together.js",
 "js/view-deck.js",
 "js/view-settings.js",
 "js/view-users.js",
 "js/view-about.js",
 "js/app.js",
 "manifest.webmanifest",
 "data/cards.js",
 "icons/icon-192.png",
 "icons/icon-maskable-512.png",
 "icons/apple-touch-icon.png",
 "icons/favicon-32.png",
 "icons/icon.svg",
 "js/install.js",
 "icons/icon-512.png",
 "data/images/01_ACTIVISM.jpg",
 "data/images/02_ADVENTURE.jpg",
 "data/images/03_AMBITION.jpg",
 "data/images/04_ASSERTIVENESS.jpg",
 "data/images/05_BEAUTY.jpg",
 "data/images/06_CAREER.jpg",
 "data/images/07_CIVIC_ENGAGEMENT.jpg",
 "data/images/08_CIVILITY.jpg",
 "data/images/09_COLLABORATION.jpg",
 "data/images/10_COMPASSION.jpg",
 "data/images/11_CONTRIBUTION.jpg",
 "data/images/12_COURAGE.jpg",
 "data/images/13_CREATIVITY.jpg",
 "data/images/14_CURIOSITY.jpg",
 "data/images/15_DIVERSITY.jpg",
 "data/images/16_EDUCATION.jpg",
 "data/images/17_EMPATHY.jpg",
 "data/images/18_ENVIRONMENT.jpg",
 "data/images/19_EQUALITY.jpg",
 "data/images/20_EXCELLENCE.jpg",
 "data/images/21_FAMILY.jpg",
 "data/images/22_FORGIVENESS.jpg",
 "data/images/23_FUN.jpg",
 "data/images/24_GENEROSITY.jpg",
 "data/images/25_GENUINENESS.jpg",
 "data/images/26_GRATITUDE.jpg",
 "data/images/27_GROWTH.jpg",
 "data/images/28_HARMONY.jpg",
 "data/images/29_HEALTH.jpg",
 "data/images/30_HONESTY.jpg",
 "data/images/31_HUMILITY.jpg",
 "data/images/32_HUMOR.jpg",
 "data/images/33_INCLUSIVENESS.jpg",
 "data/images/34_INDEPENDENCE.jpg",
 "data/images/35_INTEGRITY.jpg",
 "data/images/36_INTUITION.jpg",
 "data/images/37_JUSTICE.jpg",
 "data/images/38_KINDNESS.jpg",
 "data/images/39_KNOWLEDGE.jpg",
 "data/images/40_LEADERSHIP.jpg",
 "data/images/41_LOVE.jpg",
 "data/images/42_LOYALTY.jpg",
 "data/images/43_MINDFULNESS.jpg",
 "data/images/44_MODERATION.jpg",
 "data/images/45_NON_CONFORMITY.jpg",
 "data/images/46_OPENNESS.jpg",
 "data/images/47_OPTIMISM.jpg",
 "data/images/48_ORDER.jpg",
 "data/images/49_PARENTING.jpg",
 "data/images/50_PASSION.jpg",
 "data/images/51_PATIENCE.jpg",
 "data/images/52_PURPOSE.jpg",
 "data/images/53_RATIONALITY.jpg",
 "data/images/54_RESILIENCE.jpg",
 "data/images/55_RESPECT.jpg",
 "data/images/56_RESPONSIBILITY.jpg",
 "data/images/57_RISK_TAKING.jpg",
 "data/images/58_ROMANCE.jpg",
 "data/images/59_SELF_AWARENESS.jpg",
 "data/images/60_SELF_DISCIPLINE.jpg",
 "data/images/61_SELF_EXPRESSION.jpg",
 "data/images/62_SELF_RESPECT.jpg",
 "data/images/63_SERVICE.jpg",
 "data/images/64_SIMPLICITY.jpg",
 "data/images/65_SOCIAL_CONNECTION.jpg",
 "data/images/66_SOLITUDE.jpg",
 "data/images/67_SPIRITUALITY.jpg",
 "data/images/68_STABILITY.jpg",
 "data/images/69_SUCCESS.jpg",
 "data/images/70_THRIFT.jpg",
 "data/images/71_VULNERABILITY.jpg",
 "data/images/72_WISDOM.jpg",
 "data/images/73_WORK_ETHIC.jpg"
];
self.addEventListener("install", e => e.waitUntil(caches.open(VERSION).then(c => c.addAll(ASSETS.map(u => new Request(u, {cache: "reload"}))))));
// Pages from before v6 have no Update toast (they auto-reload on controllerchange): take over immediately once.
self.addEventListener("install", e => e.waitUntil(caches.keys().then(ks => { if (ks.some(k => /^v[1-5]$/.test(k))) return self.skipWaiting(); })));
// New versions wait until the user taps "Update" in the app toast.
self.addEventListener("message", e => { if (e.data === "skipWaiting") self.skipWaiting(); });
self.addEventListener("activate", e => e.waitUntil(caches.keys().then(ks => Promise.all(ks.filter(k => k !== VERSION).map(k => caches.delete(k)))).then(() => self.clients.claim())));
self.addEventListener("fetch", e => {
  if (e.request.method !== "GET") return;
  const url = new URL(e.request.url);
  // images: cache-first; app shell/code: network-first so updates land without a VERSION bump
  if (url.origin === location.origin && !/\.(jpg|png|svg)$/.test(url.pathname)){
    e.respondWith(fetch(e.request, {cache: "no-cache"}).then(r => { const c = r.clone(); caches.open(VERSION).then(k => k.put(e.request, c)); return r; })
      .catch(() => caches.match(e.request, {ignoreSearch: true})));
    return;
  }
  e.respondWith(caches.match(e.request, {ignoreSearch: true}).then(r => r || fetch(e.request)));
});
